/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label37;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label35;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label36;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label38;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label9;
  GtkWidget *label1;
  GtkWidget *fixed5;
  GtkWidget *fixed13;
  GtkWidget *entry96;
  GtkWidget *entry97;
  GtkWidget *entry98;
  GtkObject *spinbutton24_adj;
  GtkWidget *spinbutton24;
  GtkObject *spinbutton25_adj;
  GtkWidget *spinbutton25;
  GtkObject *spinbutton26_adj;
  GtkWidget *spinbutton26;
  GtkWidget *entry99;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry102;
  GtkWidget *entry103;
  GtkWidget *entry104;
  GtkWidget *entry105;
  GtkWidget *button56;
  GtkWidget *alignment53;
  GtkWidget *hbox53;
  GtkWidget *image53;
  GtkWidget *label203;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton15;
  GtkWidget *button57;
  GtkWidget *alignment54;
  GtkWidget *hbox54;
  GtkWidget *image54;
  GtkWidget *label204;
  GtkWidget *button58;
  GtkWidget *alignment55;
  GtkWidget *hbox55;
  GtkWidget *image55;
  GtkWidget *label205;
  GtkWidget *button59;
  GtkWidget *alignment56;
  GtkWidget *hbox56;
  GtkWidget *image56;
  GtkWidget *label206;
  GtkWidget *label208;
  GtkWidget *label209;
  GtkWidget *label210;
  GtkWidget *label211;
  GtkWidget *label212;
  GtkWidget *label214;
  GtkWidget *label215;
  GtkWidget *label217;
  GtkWidget *label218;
  GtkWidget *label216;
  GtkWidget *label213;
  GtkWidget *label207;
  GtkWidget *label219;
  GtkWidget *label2;
  GtkWidget *fixed7;
  GtkWidget *entry67;
  GtkWidget *button29;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label127;
  GtkWidget *button30;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label128;
  GtkWidget *button27;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label125;
  GtkWidget *button28;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label126;
  GtkWidget *label123;
  GtkWidget *label124;
  GtkWidget *label3;
  GtkWidget *fixed8;
  GtkWidget *button32;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label131;
  GtkWidget *button31;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label130;
  GtkWidget *button34;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label133;
  GtkWidget *button36;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image33;
  GtkWidget *label135;
  GtkWidget *button33;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label132;
  GtkWidget *button35;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image32;
  GtkWidget *label134;
  GtkWidget *label129;
  GtkWidget *label4;
  GtkWidget *fixed9;
  GtkWidget *treeview1;
  GtkWidget *button37;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image34;
  GtkWidget *label137;
  GtkWidget *button39;
  GtkWidget *alignment36;
  GtkWidget *hbox36;
  GtkWidget *image36;
  GtkWidget *label139;
  GtkWidget *button38;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image35;
  GtkWidget *label138;
  GtkWidget *label136;
  GtkWidget *label5;
  GtkWidget *fixed10;
  GtkWidget *entry68;
  GtkWidget *button40;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image37;
  GtkWidget *label142;
  GtkWidget *button41;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image38;
  GtkWidget *label143;
  GtkWidget *button42;
  GtkWidget *alignment39;
  GtkWidget *hbox39;
  GtkWidget *image39;
  GtkWidget *label144;
  GtkWidget *label141;
  GtkWidget *label140;
  GtkWidget *label6;
  GtkWidget *fixed11;
  GtkWidget *treeview2;
  GtkWidget *button43;
  GtkWidget *alignment40;
  GtkWidget *hbox40;
  GtkWidget *image40;
  GtkWidget *label146;
  GtkWidget *button44;
  GtkWidget *alignment41;
  GtkWidget *hbox41;
  GtkWidget *image41;
  GtkWidget *label147;
  GtkWidget *button45;
  GtkWidget *alignment42;
  GtkWidget *hbox42;
  GtkWidget *image42;
  GtkWidget *label148;
  GtkWidget *label145;
  GtkWidget *label7;
  GtkWidget *fixed14;
  GtkWidget *label236;
  GtkWidget *label237;
  GtkWidget *checkbutton3;
  GtkWidget *alignment57;
  GtkWidget *hbox57;
  GtkWidget *image57;
  GtkWidget *label238;
  GtkWidget *checkbutton4;
  GtkWidget *alignment58;
  GtkWidget *hbox58;
  GtkWidget *image58;
  GtkWidget *label239;
  GtkWidget *checkbutton5;
  GtkWidget *alignment59;
  GtkWidget *hbox59;
  GtkWidget *image59;
  GtkWidget *label240;
  GtkWidget *label241;
  GtkWidget *label8;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1272, 1096);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 392, 136);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 392, 200);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 392, 272);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 312, 336);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 392, 336);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3, 480, 336);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 440, 488);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 992, 128);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 1000, 200);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 1000, 272);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 1008, 336);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9, 1008, 416);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed3), entry10, 1016, 488);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 32, 872);
  gtk_widget_set_size_request (button3, 160, 61);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox3), label37, FALSE, FALSE, 0);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 456, 416);
  gtk_widget_set_size_request (radiobutton2, 152, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 320, 416);
  gtk_widget_set_size_request (radiobutton1, 136, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 712, 656);
  gtk_widget_set_size_request (button1, 152, 61);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Ajouter </span>"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox1), label35, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 712, 744);
  gtk_widget_set_size_request (button2, 152, 61);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("<span color='darkred'>annuler </span>"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox2), label36, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 1072, 864);
  gtk_widget_set_size_request (button4, 168, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox4), label38, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Nom :</span></span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 256, 136);
  gtk_widget_set_size_request (label10, 80, 33);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label11 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Pr\303\251nom :</span></span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 232, 184);
  gtk_widget_set_size_request (label11, 168, 56);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label12 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Num\303\251ro CIN:</span></span>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 208, 248);
  gtk_widget_set_size_request (label12, 184, 64);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label13 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Date de naissance:</span></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 48, 312);
  gtk_widget_set_size_request (label13, 248, 65);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label14 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Sexe:</span></span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 136, 392);
  gtk_widget_set_size_request (label14, 152, 80);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label15 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">\303\211tat civil</span></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 104, 480);
  gtk_widget_set_size_request (label15, 224, 57);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">\303\211tat sanitaire:</span></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 752, 112);
  gtk_widget_set_size_request (label16, 216, 57);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Num\303\251ro de t\303\251l\303\251phone:</span></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 712, 200);
  gtk_widget_set_size_request (label17, 280, 41);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Adresse mail:</span></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 744, 256);
  gtk_widget_set_size_request (label18, 208, 56);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">poste d\303\251sirant:</span></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 736, 328);
  gtk_widget_set_size_request (label19, 224, 49);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Login :</span></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 768, 408);
  gtk_widget_set_size_request (label20, 168, 57);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label21 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Mot de passse:</span></span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 760, 480);
  gtk_widget_set_size_request (label21, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label9 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">Ajouter un agent:</span></span></u>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 480, 24);
  gtk_widget_set_size_request (label9, 336, 72);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label1 = gtk_label_new (_("<span color='navy'>ajouter </span>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed13, 0, 0);
  gtk_widget_set_size_request (fixed13, 0, 0);

  entry96 = gtk_entry_new ();
  gtk_widget_show (entry96);
  gtk_fixed_put (GTK_FIXED (fixed13), entry96, 392, 136);
  gtk_widget_set_size_request (entry96, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry96), 8226);

  entry97 = gtk_entry_new ();
  gtk_widget_show (entry97);
  gtk_fixed_put (GTK_FIXED (fixed13), entry97, 392, 200);
  gtk_widget_set_size_request (entry97, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry97), 8226);

  entry98 = gtk_entry_new ();
  gtk_widget_show (entry98);
  gtk_fixed_put (GTK_FIXED (fixed13), entry98, 392, 272);
  gtk_widget_set_size_request (entry98, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry98), 8226);

  spinbutton24_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton24 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton24_adj), 1, 0);
  gtk_widget_show (spinbutton24);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton24, 312, 336);
  gtk_widget_set_size_request (spinbutton24, 60, 27);

  spinbutton25_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton25 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton25_adj), 1, 0);
  gtk_widget_show (spinbutton25);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton25, 392, 336);
  gtk_widget_set_size_request (spinbutton25, 60, 27);

  spinbutton26_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton26 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton26_adj), 1, 0);
  gtk_widget_show (spinbutton26);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton26, 480, 336);
  gtk_widget_set_size_request (spinbutton26, 60, 27);

  entry99 = gtk_entry_new ();
  gtk_widget_show (entry99);
  gtk_fixed_put (GTK_FIXED (fixed13), entry99, 440, 488);
  gtk_widget_set_size_request (entry99, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry99), 8226);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed13), entry100, 992, 128);
  gtk_widget_set_size_request (entry100, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed13), entry101, 1000, 200);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed13), entry102, 1000, 272);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  entry103 = gtk_entry_new ();
  gtk_widget_show (entry103);
  gtk_fixed_put (GTK_FIXED (fixed13), entry103, 1008, 336);
  gtk_widget_set_size_request (entry103, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry103), 8226);

  entry104 = gtk_entry_new ();
  gtk_widget_show (entry104);
  gtk_fixed_put (GTK_FIXED (fixed13), entry104, 1008, 416);
  gtk_widget_set_size_request (entry104, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry104), 8226);

  entry105 = gtk_entry_new ();
  gtk_widget_show (entry105);
  gtk_fixed_put (GTK_FIXED (fixed13), entry105, 1016, 488);
  gtk_widget_set_size_request (entry105, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry105), 8226);

  button56 = gtk_button_new ();
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed13), button56, 32, 872);
  gtk_widget_set_size_request (button56, 160, 61);

  alignment53 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment53);
  gtk_container_add (GTK_CONTAINER (button56), alignment53);

  hbox53 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox53);
  gtk_container_add (GTK_CONTAINER (alignment53), hbox53);

  image53 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox53), image53, FALSE, FALSE, 0);

  label203 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label203);
  gtk_box_pack_start (GTK_BOX (hbox53), label203, FALSE, FALSE, 0);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton14);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton14, 456, 416);
  gtk_widget_set_size_request (radiobutton14, 152, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton15 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton15);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton15, 320, 416);
  gtk_widget_set_size_request (radiobutton15, 136, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton15), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton15));

  button57 = gtk_button_new ();
  gtk_widget_show (button57);
  gtk_fixed_put (GTK_FIXED (fixed13), button57, 712, 656);
  gtk_widget_set_size_request (button57, 152, 61);

  alignment54 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment54);
  gtk_container_add (GTK_CONTAINER (button57), alignment54);

  hbox54 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox54);
  gtk_container_add (GTK_CONTAINER (alignment54), hbox54);

  image54 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox54), image54, FALSE, FALSE, 0);

  label204 = gtk_label_new (_("<span color='darkred'>modifier </span>"));
  gtk_widget_show (label204);
  gtk_box_pack_start (GTK_BOX (hbox54), label204, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label204), TRUE);

  button58 = gtk_button_new ();
  gtk_widget_show (button58);
  gtk_fixed_put (GTK_FIXED (fixed13), button58, 712, 744);
  gtk_widget_set_size_request (button58, 152, 61);

  alignment55 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (button58), alignment55);

  hbox55 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox55);
  gtk_container_add (GTK_CONTAINER (alignment55), hbox55);

  image55 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox55), image55, FALSE, FALSE, 0);

  label205 = gtk_label_new (_("<span color='darkred'>annuler </span>"));
  gtk_widget_show (label205);
  gtk_box_pack_start (GTK_BOX (hbox55), label205, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label205), TRUE);

  button59 = gtk_button_new ();
  gtk_widget_show (button59);
  gtk_fixed_put (GTK_FIXED (fixed13), button59, 1072, 864);
  gtk_widget_set_size_request (button59, 168, 64);

  alignment56 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment56);
  gtk_container_add (GTK_CONTAINER (button59), alignment56);

  hbox56 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox56);
  gtk_container_add (GTK_CONTAINER (alignment56), hbox56);

  image56 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox56), image56, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox56), label206, FALSE, FALSE, 0);

  label208 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Pr\303\251nom :</span></span>"));
  gtk_widget_show (label208);
  gtk_fixed_put (GTK_FIXED (fixed13), label208, 232, 184);
  gtk_widget_set_size_request (label208, 168, 56);
  gtk_label_set_use_markup (GTK_LABEL (label208), TRUE);

  label209 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Num\303\251ro CIN:</span></span>"));
  gtk_widget_show (label209);
  gtk_fixed_put (GTK_FIXED (fixed13), label209, 208, 248);
  gtk_widget_set_size_request (label209, 184, 64);
  gtk_label_set_use_markup (GTK_LABEL (label209), TRUE);

  label210 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Date de naissance:</span></span>"));
  gtk_widget_show (label210);
  gtk_fixed_put (GTK_FIXED (fixed13), label210, 48, 312);
  gtk_widget_set_size_request (label210, 248, 65);
  gtk_label_set_use_markup (GTK_LABEL (label210), TRUE);

  label211 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Sexe:</span></span>"));
  gtk_widget_show (label211);
  gtk_fixed_put (GTK_FIXED (fixed13), label211, 136, 392);
  gtk_widget_set_size_request (label211, 152, 80);
  gtk_label_set_use_markup (GTK_LABEL (label211), TRUE);

  label212 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">\303\211tat civil</span></span>"));
  gtk_widget_show (label212);
  gtk_fixed_put (GTK_FIXED (fixed13), label212, 104, 480);
  gtk_widget_set_size_request (label212, 224, 57);
  gtk_label_set_use_markup (GTK_LABEL (label212), TRUE);

  label214 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Num\303\251ro de t\303\251l\303\251phone:</span></span>"));
  gtk_widget_show (label214);
  gtk_fixed_put (GTK_FIXED (fixed13), label214, 712, 200);
  gtk_widget_set_size_request (label214, 280, 41);
  gtk_label_set_use_markup (GTK_LABEL (label214), TRUE);

  label215 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Adresse mail:</span></span>"));
  gtk_widget_show (label215);
  gtk_fixed_put (GTK_FIXED (fixed13), label215, 744, 256);
  gtk_widget_set_size_request (label215, 208, 56);
  gtk_label_set_use_markup (GTK_LABEL (label215), TRUE);

  label217 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Login :</span></span>"));
  gtk_widget_show (label217);
  gtk_fixed_put (GTK_FIXED (fixed13), label217, 768, 408);
  gtk_widget_set_size_request (label217, 168, 57);
  gtk_label_set_use_markup (GTK_LABEL (label217), TRUE);

  label218 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Mot de passse:</span></span>"));
  gtk_widget_show (label218);
  gtk_fixed_put (GTK_FIXED (fixed13), label218, 760, 480);
  gtk_widget_set_size_request (label218, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label218), TRUE);

  label216 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">poste actuel:</span></span>"));
  gtk_widget_show (label216);
  gtk_fixed_put (GTK_FIXED (fixed13), label216, 744, 328);
  gtk_widget_set_size_request (label216, 224, 49);
  gtk_label_set_use_markup (GTK_LABEL (label216), TRUE);

  label213 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">\303\211tat sanitaire:</span></span>"));
  gtk_widget_show (label213);
  gtk_fixed_put (GTK_FIXED (fixed13), label213, 752, 112);
  gtk_widget_set_size_request (label213, 216, 57);
  gtk_label_set_use_markup (GTK_LABEL (label213), TRUE);

  label207 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Nom :</span></span>"));
  gtk_widget_show (label207);
  gtk_fixed_put (GTK_FIXED (fixed13), label207, 256, 136);
  gtk_widget_set_size_request (label207, 80, 33);
  gtk_label_set_use_markup (GTK_LABEL (label207), TRUE);

  label219 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">Modifier les informations d'un agent:</span></span></u>"));
  gtk_widget_show (label219);
  gtk_fixed_put (GTK_FIXED (fixed13), label219, 344, 32);
  gtk_widget_set_size_request (label219, 712, 64);
  gtk_label_set_use_markup (GTK_LABEL (label219), TRUE);

  label2 = gtk_label_new (_("<span color='navy'>modifier</span>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry67 = gtk_entry_new ();
  gtk_widget_show (entry67);
  gtk_fixed_put (GTK_FIXED (fixed7), entry67, 776, 336);
  gtk_widget_set_size_request (entry67, 328, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry67), 8226);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed7), button29, 24, 848);
  gtk_widget_set_size_request (button29, 168, 69);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button29), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label127 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label127);
  gtk_box_pack_start (GTK_BOX (hbox26), label127, FALSE, FALSE, 0);

  button30 = gtk_button_new ();
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed7), button30, 1376, 848);
  gtk_widget_set_size_request (button30, 178, 77);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button30), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label128 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label128);
  gtk_box_pack_start (GTK_BOX (hbox27), label128, FALSE, FALSE, 0);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed7), button27, 736, 608);
  gtk_widget_set_size_request (button27, 202, 77);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button27), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label125 = gtk_label_new_with_mnemonic (_("<span color='darkred'>supprimer </span>"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox24), label125, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed7), button28, 736, 704);
  gtk_widget_set_size_request (button28, 200, 72);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button28), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_("<span color='darkred'>annuler </span>"));
  gtk_widget_show (label126);
  gtk_box_pack_start (GTK_BOX (hbox25), label126, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label126), TRUE);

  label123 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">SUPPRIMER un agent:</span></span></u>"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed7), label123, 528, 24);
  gtk_widget_set_size_request (label123, 568, 184);
  gtk_label_set_use_markup (GTK_LABEL (label123), TRUE);

  label124 = gtk_label_new (_("<span  font_size=\"20000\" > <span foreground=\"black\">Veillez entrer votre num\303\251ro CIN:</span></span>"));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed7), label124, 320, 336);
  gtk_widget_set_size_request (label124, 416, 33);
  gtk_label_set_use_markup (GTK_LABEL (label124), TRUE);

  label3 = gtk_label_new (_("<span color='navy'>supprimer</span>"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed8), button32, 872, 216);
  gtk_widget_set_size_request (button32, 288, 112);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button32), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Modifier </span>"));
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (hbox29), label131, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label131), TRUE);

  button31 = gtk_button_new ();
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed8), button31, 528, 216);
  gtk_widget_set_size_request (button31, 272, 112);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button31), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label130 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Ajouter </span>"));
  gtk_widget_show (label130);
  gtk_box_pack_start (GTK_BOX (hbox28), label130, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label130), TRUE);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed8), button34, 880, 400);
  gtk_widget_set_size_request (button34, 272, 109);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button34), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label133 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Rechercher </span>"));
  gtk_widget_show (label133);
  gtk_box_pack_start (GTK_BOX (hbox31), label133, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  button36 = gtk_button_new ();
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed8), button36, 888, 584);
  gtk_widget_set_size_request (button36, 264, 112);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button36), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image33 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox33), image33, FALSE, FALSE, 0);

  label135 = gtk_label_new_with_mnemonic (_("\n<span color='darkred'>Afficher liste de r\303\251s\303\251rvation </span>"));
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (hbox33), label135, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label135), TRUE);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed8), button33, 536, 400);
  gtk_widget_set_size_request (button33, 280, 112);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button33), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label132 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Supprimer </span>"));
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (hbox30), label132, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label132), TRUE);

  button35 = gtk_button_new ();
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed8), button35, 544, 584);
  gtk_widget_set_size_request (button35, 272, 112);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button35), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image32 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox32), image32, FALSE, FALSE, 0);

  label134 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Afficher </span>"));
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (hbox32), label134, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label134), TRUE);

  label129 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">Entrez votre choix:</span></span></u>"));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed8), label129, 576, 8);
  gtk_widget_set_size_request (label129, 448, 129);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  label4 = gtk_label_new (_("<span color='navy'>menu</span>"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview1, 248, 240);
  gtk_widget_set_size_request (treeview1, 1048, 448);

  button37 = gtk_button_new ();
  gtk_widget_show (button37);
  gtk_fixed_put (GTK_FIXED (fixed9), button37, 760, 840);
  gtk_widget_set_size_request (button37, 184, 69);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button37), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image34 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox34), image34, FALSE, FALSE, 0);

  label137 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Afficher </span>"));
  gtk_widget_show (label137);
  gtk_box_pack_start (GTK_BOX (hbox34), label137, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label137), TRUE);

  button39 = gtk_button_new ();
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed9), button39, 1368, 840);
  gtk_widget_set_size_request (button39, 162, 69);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (button39), alignment36);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox36);

  image36 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox36), image36, FALSE, FALSE, 0);

  label139 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox36), label139, FALSE, FALSE, 0);

  button38 = gtk_button_new ();
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed9), button38, 48, 840);
  gtk_widget_set_size_request (button38, 176, 72);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (button38), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image35 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox35), image35, FALSE, FALSE, 0);

  label138 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (hbox35), label138, FALSE, FALSE, 0);

  label136 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">Afficher le tableau contenant les  agents:</span></span></u>"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed9), label136, 240, 32);
  gtk_widget_set_size_request (label136, 1104, 200);
  gtk_label_set_use_markup (GTK_LABEL (label136), TRUE);

  label5 = gtk_label_new (_("<span color='navy'>afficher</span>"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entry68 = gtk_entry_new ();
  gtk_widget_show (entry68);
  gtk_fixed_put (GTK_FIXED (fixed10), entry68, 704, 280);
  gtk_widget_set_size_request (entry68, 352, 64);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry68), 8226);

  button40 = gtk_button_new ();
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed10), button40, 632, 488);
  gtk_widget_set_size_request (button40, 296, 93);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (button40), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image37 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox37), image37, FALSE, FALSE, 0);

  label142 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Rechercher </span>"));
  gtk_widget_show (label142);
  gtk_box_pack_start (GTK_BOX (hbox37), label142, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label142), TRUE);

  button41 = gtk_button_new ();
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed10), button41, 32, 856);
  gtk_widget_set_size_request (button41, 200, 69);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (button41), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image38 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox38), image38, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("Pr\303\251c\303\251dent"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox38), label143, FALSE, FALSE, 0);

  button42 = gtk_button_new ();
  gtk_widget_show (button42);
  gtk_fixed_put (GTK_FIXED (fixed10), button42, 1352, 840);
  gtk_widget_set_size_request (button42, 186, 77);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (button42), alignment39);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox39);

  image39 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox39), image39, FALSE, FALSE, 0);

  label144 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox39), label144, FALSE, FALSE, 0);

  label141 = gtk_label_new (_("\n\n\n\n<span  font_size=\"20000\" > <span foreground=\"black\">Entrez le num\303\251ro CIN de l'agent :</span></span>"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed10), label141, 264, 176);
  gtk_widget_set_size_request (label141, 424, 200);
  gtk_label_set_use_markup (GTK_LABEL (label141), TRUE);

  label140 = gtk_label_new (_("\n<u><span  font_size=\"20000\" > <span foreground=\"navy\">Recherche d'un agent :</span></span></u>"));
  gtk_widget_show (label140);
  gtk_fixed_put (GTK_FIXED (fixed10), label140, 528, 56);
  gtk_widget_set_size_request (label140, 464, 97);
  gtk_label_set_use_markup (GTK_LABEL (label140), TRUE);

  label6 = gtk_label_new (_("<span color='navy'>chercher</span>"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label6);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview2, 144, 176);
  gtk_widget_set_size_request (treeview2, 1200, 536);

  button43 = gtk_button_new ();
  gtk_widget_show (button43);
  gtk_fixed_put (GTK_FIXED (fixed11), button43, 744, 848);
  gtk_widget_set_size_request (button43, 210, 77);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (button43), alignment40);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox40);

  image40 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox40), image40, FALSE, FALSE, 0);

  label146 = gtk_label_new_with_mnemonic (_("<span color='darkred'>Afficher </span>"));
  gtk_widget_show (label146);
  gtk_box_pack_start (GTK_BOX (hbox40), label146, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);

  button44 = gtk_button_new ();
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed11), button44, 104, 864);
  gtk_widget_set_size_request (button44, 184, 69);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (button44), alignment41);

  hbox41 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox41);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox41);

  image41 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox41), image41, FALSE, FALSE, 0);

  label147 = gtk_label_new_with_mnemonic (_("Pr\303\251cedent"));
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (hbox41), label147, FALSE, FALSE, 0);

  button45 = gtk_button_new ();
  gtk_widget_show (button45);
  gtk_fixed_put (GTK_FIXED (fixed11), button45, 1344, 848);
  gtk_widget_set_size_request (button45, 178, 77);

  alignment42 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment42);
  gtk_container_add (GTK_CONTAINER (button45), alignment42);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment42), hbox42);

  image42 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox42), image42, FALSE, FALSE, 0);

  label148 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox42), label148, FALSE, FALSE, 0);

  label145 = gtk_label_new (_("<u><span  font_size=\"20000\" > <span foreground=\"navy\">AFFICHER LA LISTE DES R\303\211S\303\211RVATIONS FAITES PAR LES CITOYENS :</span></span></u>"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed11), label145, 312, 32);
  gtk_widget_set_size_request (label145, 832, 129);
  gtk_label_set_use_markup (GTK_LABEL (label145), TRUE);

  label7 = gtk_label_new (_("<span color='navy'>afficherres</span>"));
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label7);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed14);

  label236 = gtk_label_new ("");
  gtk_widget_show (label236);
  gtk_fixed_put (GTK_FIXED (fixed14), label236, 464, 32);
  gtk_widget_set_size_request (label236, 57, 17);

  label237 = gtk_label_new_with_mnemonic (_("<span  font_size=\"20000\" > <span foreground=\"black\">                                                              Merci \303\240 nos employ\303\251s !\n\n\n                 Votre engagement et votre travail sont essentiels \303\240 notre r\303\251ussite. \n\n\n\nNous sommes reconnaissants pour tout ce que vous faites chaque jour pour am\303\251liorer notre service.\n\n\n                                                                      Bravo et merci !\n                                            \n\n                                                                    L'\303\251quipe de Parky\n\n\n\n  L'avis de nos administrateurs / administratrices de notre service est important pour nous !</span></span>"));
  gtk_widget_show (label237);
  gtk_fixed_put (GTK_FIXED (fixed14), label237, 16, 0);
  gtk_widget_set_size_request (label237, 1240, 656);
  gtk_label_set_use_markup (GTK_LABEL (label237), TRUE);

  checkbutton3 = gtk_check_button_new ();
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton3, 840, 832);
  gtk_widget_set_size_request (checkbutton3, 134, 24);

  alignment57 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment57);
  gtk_container_add (GTK_CONTAINER (checkbutton3), alignment57);

  hbox57 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox57);
  gtk_container_add (GTK_CONTAINER (alignment57), hbox57);

  image57 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox57), image57, FALSE, FALSE, 0);

  label238 = gtk_label_new (_("<span color='darkred'>mauvais </span>"));
  gtk_widget_show (label238);
  gtk_box_pack_start (GTK_BOX (hbox57), label238, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label238), TRUE);

  checkbutton4 = gtk_check_button_new ();
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton4, 632, 824);
  gtk_widget_set_size_request (checkbutton4, 144, 40);

  alignment58 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment58);
  gtk_container_add (GTK_CONTAINER (checkbutton4), alignment58);

  hbox58 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox58);
  gtk_container_add (GTK_CONTAINER (alignment58), hbox58);

  image58 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox58), image58, FALSE, FALSE, 0);

  label239 = gtk_label_new (_("<span color='darkred'>pas mal </span>"));
  gtk_widget_show (label239);
  gtk_box_pack_start (GTK_BOX (hbox58), label239, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label239), TRUE);

  checkbutton5 = gtk_check_button_new ();
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton5, 456, 832);
  gtk_widget_set_size_request (checkbutton5, 118, 24);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (checkbutton5), alignment59);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox59);

  image59 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox59), image59, FALSE, FALSE, 0);

  label240 = gtk_label_new (_("<span color='darkred'>excellent </span>"));
  gtk_widget_show (label240);
  gtk_box_pack_start (GTK_BOX (hbox59), label240, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label240), TRUE);

  label241 = gtk_label_new_with_mnemonic (_("<span  font_size=\"20000\" > <span foreground=\"black\">Saisir votre choix :</span></span>"));
  gtk_widget_show (label241);
  gtk_fixed_put (GTK_FIXED (fixed14), label241, 168, 792);
  gtk_widget_set_size_request (label241, 272, 97);
  gtk_label_set_use_markup (GTK_LABEL (label241), TRUE);

  label8 = gtk_label_new (_("<span color='navy'>goodbye</span>"));
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 7), label8);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window1, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window1, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window1, entry96, "entry96");
  GLADE_HOOKUP_OBJECT (window1, entry97, "entry97");
  GLADE_HOOKUP_OBJECT (window1, entry98, "entry98");
  GLADE_HOOKUP_OBJECT (window1, spinbutton24, "spinbutton24");
  GLADE_HOOKUP_OBJECT (window1, spinbutton25, "spinbutton25");
  GLADE_HOOKUP_OBJECT (window1, spinbutton26, "spinbutton26");
  GLADE_HOOKUP_OBJECT (window1, entry99, "entry99");
  GLADE_HOOKUP_OBJECT (window1, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (window1, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (window1, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (window1, entry103, "entry103");
  GLADE_HOOKUP_OBJECT (window1, entry104, "entry104");
  GLADE_HOOKUP_OBJECT (window1, entry105, "entry105");
  GLADE_HOOKUP_OBJECT (window1, button56, "button56");
  GLADE_HOOKUP_OBJECT (window1, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (window1, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (window1, image53, "image53");
  GLADE_HOOKUP_OBJECT (window1, label203, "label203");
  GLADE_HOOKUP_OBJECT (window1, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (window1, radiobutton15, "radiobutton15");
  GLADE_HOOKUP_OBJECT (window1, button57, "button57");
  GLADE_HOOKUP_OBJECT (window1, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (window1, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (window1, image54, "image54");
  GLADE_HOOKUP_OBJECT (window1, label204, "label204");
  GLADE_HOOKUP_OBJECT (window1, button58, "button58");
  GLADE_HOOKUP_OBJECT (window1, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (window1, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (window1, image55, "image55");
  GLADE_HOOKUP_OBJECT (window1, label205, "label205");
  GLADE_HOOKUP_OBJECT (window1, button59, "button59");
  GLADE_HOOKUP_OBJECT (window1, alignment56, "alignment56");
  GLADE_HOOKUP_OBJECT (window1, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (window1, image56, "image56");
  GLADE_HOOKUP_OBJECT (window1, label206, "label206");
  GLADE_HOOKUP_OBJECT (window1, label208, "label208");
  GLADE_HOOKUP_OBJECT (window1, label209, "label209");
  GLADE_HOOKUP_OBJECT (window1, label210, "label210");
  GLADE_HOOKUP_OBJECT (window1, label211, "label211");
  GLADE_HOOKUP_OBJECT (window1, label212, "label212");
  GLADE_HOOKUP_OBJECT (window1, label214, "label214");
  GLADE_HOOKUP_OBJECT (window1, label215, "label215");
  GLADE_HOOKUP_OBJECT (window1, label217, "label217");
  GLADE_HOOKUP_OBJECT (window1, label218, "label218");
  GLADE_HOOKUP_OBJECT (window1, label216, "label216");
  GLADE_HOOKUP_OBJECT (window1, label213, "label213");
  GLADE_HOOKUP_OBJECT (window1, label207, "label207");
  GLADE_HOOKUP_OBJECT (window1, label219, "label219");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, entry67, "entry67");
  GLADE_HOOKUP_OBJECT (window1, button29, "button29");
  GLADE_HOOKUP_OBJECT (window1, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window1, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, label127, "label127");
  GLADE_HOOKUP_OBJECT (window1, button30, "button30");
  GLADE_HOOKUP_OBJECT (window1, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window1, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window1, image27, "image27");
  GLADE_HOOKUP_OBJECT (window1, label128, "label128");
  GLADE_HOOKUP_OBJECT (window1, button27, "button27");
  GLADE_HOOKUP_OBJECT (window1, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window1, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label125, "label125");
  GLADE_HOOKUP_OBJECT (window1, button28, "button28");
  GLADE_HOOKUP_OBJECT (window1, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window1, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label126, "label126");
  GLADE_HOOKUP_OBJECT (window1, label123, "label123");
  GLADE_HOOKUP_OBJECT (window1, label124, "label124");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window1, button32, "button32");
  GLADE_HOOKUP_OBJECT (window1, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window1, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, label131, "label131");
  GLADE_HOOKUP_OBJECT (window1, button31, "button31");
  GLADE_HOOKUP_OBJECT (window1, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window1, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, label130, "label130");
  GLADE_HOOKUP_OBJECT (window1, button34, "button34");
  GLADE_HOOKUP_OBJECT (window1, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window1, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window1, image31, "image31");
  GLADE_HOOKUP_OBJECT (window1, label133, "label133");
  GLADE_HOOKUP_OBJECT (window1, button36, "button36");
  GLADE_HOOKUP_OBJECT (window1, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window1, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (window1, image33, "image33");
  GLADE_HOOKUP_OBJECT (window1, label135, "label135");
  GLADE_HOOKUP_OBJECT (window1, button33, "button33");
  GLADE_HOOKUP_OBJECT (window1, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window1, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window1, image30, "image30");
  GLADE_HOOKUP_OBJECT (window1, label132, "label132");
  GLADE_HOOKUP_OBJECT (window1, button35, "button35");
  GLADE_HOOKUP_OBJECT (window1, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window1, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window1, image32, "image32");
  GLADE_HOOKUP_OBJECT (window1, label134, "label134");
  GLADE_HOOKUP_OBJECT (window1, label129, "label129");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, button37, "button37");
  GLADE_HOOKUP_OBJECT (window1, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (window1, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window1, image34, "image34");
  GLADE_HOOKUP_OBJECT (window1, label137, "label137");
  GLADE_HOOKUP_OBJECT (window1, button39, "button39");
  GLADE_HOOKUP_OBJECT (window1, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (window1, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (window1, image36, "image36");
  GLADE_HOOKUP_OBJECT (window1, label139, "label139");
  GLADE_HOOKUP_OBJECT (window1, button38, "button38");
  GLADE_HOOKUP_OBJECT (window1, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (window1, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (window1, image35, "image35");
  GLADE_HOOKUP_OBJECT (window1, label138, "label138");
  GLADE_HOOKUP_OBJECT (window1, label136, "label136");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window1, entry68, "entry68");
  GLADE_HOOKUP_OBJECT (window1, button40, "button40");
  GLADE_HOOKUP_OBJECT (window1, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (window1, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (window1, image37, "image37");
  GLADE_HOOKUP_OBJECT (window1, label142, "label142");
  GLADE_HOOKUP_OBJECT (window1, button41, "button41");
  GLADE_HOOKUP_OBJECT (window1, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (window1, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (window1, image38, "image38");
  GLADE_HOOKUP_OBJECT (window1, label143, "label143");
  GLADE_HOOKUP_OBJECT (window1, button42, "button42");
  GLADE_HOOKUP_OBJECT (window1, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (window1, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (window1, image39, "image39");
  GLADE_HOOKUP_OBJECT (window1, label144, "label144");
  GLADE_HOOKUP_OBJECT (window1, label141, "label141");
  GLADE_HOOKUP_OBJECT (window1, label140, "label140");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, button43, "button43");
  GLADE_HOOKUP_OBJECT (window1, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (window1, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (window1, image40, "image40");
  GLADE_HOOKUP_OBJECT (window1, label146, "label146");
  GLADE_HOOKUP_OBJECT (window1, button44, "button44");
  GLADE_HOOKUP_OBJECT (window1, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (window1, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (window1, image41, "image41");
  GLADE_HOOKUP_OBJECT (window1, label147, "label147");
  GLADE_HOOKUP_OBJECT (window1, button45, "button45");
  GLADE_HOOKUP_OBJECT (window1, alignment42, "alignment42");
  GLADE_HOOKUP_OBJECT (window1, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (window1, image42, "image42");
  GLADE_HOOKUP_OBJECT (window1, label148, "label148");
  GLADE_HOOKUP_OBJECT (window1, label145, "label145");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window1, label236, "label236");
  GLADE_HOOKUP_OBJECT (window1, label237, "label237");
  GLADE_HOOKUP_OBJECT (window1, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window1, alignment57, "alignment57");
  GLADE_HOOKUP_OBJECT (window1, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (window1, image57, "image57");
  GLADE_HOOKUP_OBJECT (window1, label238, "label238");
  GLADE_HOOKUP_OBJECT (window1, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window1, alignment58, "alignment58");
  GLADE_HOOKUP_OBJECT (window1, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (window1, image58, "image58");
  GLADE_HOOKUP_OBJECT (window1, label239, "label239");
  GLADE_HOOKUP_OBJECT (window1, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window1, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (window1, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (window1, image59, "image59");
  GLADE_HOOKUP_OBJECT (window1, label240, "label240");
  GLADE_HOOKUP_OBJECT (window1, label241, "label241");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");

  return window1;
}

