pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                echo 'Code récupéré depuis Git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
